import {
  cliCommands,
  type CliCommandSpec,
  type CliOptionSpec,
} from "./spec.js";

/** Shells supported by the generated completion renderer. */
export const SUPPORTED_SHELLS = ["bash", "fish", "zsh"] as const;

/** Supported shell name. */
export type CompletionShell = (typeof SUPPORTED_SHELLS)[number];

const COMMAND_NAME = "notes";

/** Whether a shell name is supported. */
export function isCompletionShell(shell: string): shell is CompletionShell {
  return (SUPPORTED_SHELLS as readonly string[]).includes(shell);
}

/** Comma-separated shell list for error messages. */
export function shellList(): string {
  return SUPPORTED_SHELLS.join(", ");
}

function bashQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function fishQuote(value: string): string {
  return `'${value.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function zshQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function allCommandWords(): string {
  return cliCommands.map((command) => command.name).join(" ");
}

function optionWords(command: CliCommandSpec): string {
  return (command.options ?? [])
    .flatMap((option) => [option.name, ...(option.short ? [option.short] : [])])
    .join(" ");
}

function commandForWord(word: string): CliCommandSpec | undefined {
  return cliCommands.find((command) => command.name === word);
}

function choiceWords(option: CliOptionSpec): string | undefined {
  return option.choices?.map((choice) => choice.value).join(" ");
}

/** Render Bash completions. */
export function renderBashCompletions(): string {
  const lines = [
    `# bash completion for ${COMMAND_NAME}`,
    `# Generated by ${COMMAND_NAME} completions bash. Do not edit by hand.`,
    "",
    `_${COMMAND_NAME}() {`,
    "  local cur prev cword command opts choices",
    "  COMPREPLY=()",
    "  cur=${COMP_WORDS[COMP_CWORD]}",
    "  prev=${COMP_WORDS[COMP_CWORD-1]}",
    "  cword=$COMP_CWORD",
    "  command=${COMP_WORDS[1]-}",
    "",
    "  if (( cword == 1 )); then",
    `    COMPREPLY=( $(compgen -W ${bashQuote(`${allCommandWords()} -h --help`)} -- "$cur") )`,
    "    return",
    "  fi",
    "",
    "  case $command in",
  ];

  for (const command of cliCommands) {
    lines.push(`    ${command.name})`);
    for (const option of command.options ?? []) {
      const choices = choiceWords(option);
      if (choices) {
        const patterns = [
          option.name,
          ...(option.short ? [option.short] : []),
        ].join("|");
        lines.push("      case $prev in");
        lines.push(`        ${patterns})`);
        lines.push(
          `          COMPREPLY=( $(compgen -W ${bashQuote(choices)} -- "$cur") )`,
        );
        lines.push("          return");
        lines.push("          ;;");
        lines.push("      esac");
      }
    }
    lines.push(`      opts=${bashQuote(optionWords(command))}`);
    lines.push("      if [[ $cur == -* ]]; then");
    lines.push('        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )');
    lines.push("      fi");
    lines.push("      return");
    lines.push("      ;;");
  }

  lines.push("  esac");
  lines.push("}");
  lines.push("");
  lines.push(`complete -F _${COMMAND_NAME} ${COMMAND_NAME}`);
  lines.push("");
  return lines.join("\n");
}

/** Render Fish completions. */
export function renderFishCompletions(): string {
  const lines = [
    `# fish completion for ${COMMAND_NAME}`,
    `# Generated by ${COMMAND_NAME} completions fish. Do not edit by hand.`,
    "",
    `complete -c ${COMMAND_NAME} -f`,
    `complete -c ${COMMAND_NAME} -s h -l help -d 'Show help message'`,
  ];

  for (const command of cliCommands) {
    lines.push(
      `complete -c ${COMMAND_NAME} -n '__fish_use_subcommand' -a ${fishQuote(command.name)} -d ${fishQuote(command.summary)}`,
    );
    const condition = `__fish_seen_subcommand_from ${command.name}`;
    for (const option of command.options ?? []) {
      const parts = ["complete", "-c", COMMAND_NAME];
      if (option.short) parts.push("-s", option.short.slice(1));
      parts.push(
        "-l",
        option.name.slice(2),
        "-d",
        fishQuote(option.description),
      );
      if (option.valueName) parts.push("-r");
      if (option.completion === "file") parts.push("-F");
      const choices = choiceWords(option);
      if (choices) parts.push("-a", fishQuote(choices));
      parts.push("-n", fishQuote(condition));
      lines.push(parts.join(" "));
    }
    for (const argument of command.arguments ?? []) {
      const choices = argument.choices?.map((choice) => choice.value).join(" ");
      if (choices) {
        lines.push(
          `complete -c ${COMMAND_NAME} -n ${fishQuote(condition)} -a ${fishQuote(choices)}`,
        );
      }
    }
  }
  return `${lines.join("\n")}\n`;
}

function zshOption(option: CliOptionSpec): string {
  const description = `[${option.description.replaceAll("]", "\\]")}]`;
  const value = option.valueName ? `:${option.valueName}:` : "";
  if (option.short) {
    return `'{${option.short},${option.name}}${description}${value}'`;
  }
  return `'${option.name}${description}${value}'`;
}

/** Render Zsh completions. */
export function renderZshCompletions(): string {
  const lines = [
    `#compdef ${COMMAND_NAME}`,
    `# Generated by ${COMMAND_NAME} completions zsh. Do not edit by hand.`,
    "",
    `local -a ${COMMAND_NAME}_commands`,
    `${COMMAND_NAME}_commands=(`,
    ...cliCommands.map(
      (command) => `  ${zshQuote(`${command.name}:${command.summary}`)}`,
    ),
    ")",
    "",
    "if (( CURRENT == 2 )); then",
    `  _describe -t commands '${COMMAND_NAME} command' ${COMMAND_NAME}_commands`,
    "  return",
    "fi",
    "",
    "local command=${words[2]}",
    "case $command in",
  ];

  for (const command of cliCommands) {
    lines.push(`  ${command.name})`);
    lines.push("    _arguments -S \\");
    const options = (command.options ?? []).map(zshOption);
    const args = (command.arguments ?? []).map((argument, index) =>
      argument.completion === "file"
        ? `      '${index + 1}:${argument.description ?? argument.name}:_files' \\`
        : `      '${index + 1}:${argument.description ?? argument.name}:' \\`,
    );
    for (const entry of [
      ...options.map((option) => `      ${option} \\`),
      ...args,
    ]) {
      lines.push(entry);
    }
    lines.push("      '*::arg:->args'");
    lines.push("    ;;");
  }

  lines.push("esac");
  lines.push("");
  return lines.join("\n");
}

/** Render completions for a supported shell. */
export function renderCompletions(shell: CompletionShell): string {
  switch (shell) {
    case "bash":
      return renderBashCompletions();
    case "fish":
      return renderFishCompletions();
    case "zsh":
      return renderZshCompletions();
  }
}
