---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  skills:
    uses: timmo001/workflows/.github/workflows/lint-agent-skills.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@82ee28374d3471231113dabc3dd436f65a47132f # 20261004.0
    with:
      scandir: ./.scripts
      severity: warning
