---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  skills:
    uses: timmo001/workflows/.github/workflows/lint-agent-skills.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master
    with:
      scandir: ./.scripts
      severity: warning
