---
name: Lint package configs

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - ".scripts/**/*PKGBUILD*"
      - ".github/workflows/lint-package-config.yml"
  pull_request:
    paths:
      - ".scripts/**/*PKGBUILD*"
      - ".github/workflows/lint-package-config.yml"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pkgbuild:
    uses: timmo001/workflows/.github/workflows/lint-arch-pkgbuild.yml@dee521f49caa2626c8adeed2af4767887b2f202b # 20261009.1
    with:
      pkgbuild-paths: |-
        .scripts/linux/PKGBUILD
        .scripts/linux/PKGBUILD.bin
      exclude-rules: redundant_makedepends
