---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  skills:
    uses: timmo001/workflows/.github/workflows/lint-agent-skills.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@005cef2e45ebffdc7c4188d89a5d783bfdb5d163 # master
    with:
      scandir: ./.scripts
      severity: warning
