---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@2cb1c90bdea4833e142eb444efddb4aabc3cbd2f # master
    permissions:
      pull-requests: write
      contents: write
