---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@7a5e6e47b7c78fc9d200fc183e9b63b9756f6ace # master
    permissions:
      pull-requests: write
      contents: write
