---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@ef14244e5cfe3a9da6441796ee7f39f2f5bde233 # master
    permissions:
      pull-requests: write
      contents: write
